package com.personal.calisthenics.core.seed

import com.personal.calisthenics.core.model.BodyRegion.*
import com.personal.calisthenics.core.model.Load.*
import com.personal.calisthenics.core.model.PeakAt.*
import com.personal.calisthenics.core.model.DoDont
import com.personal.calisthenics.core.model.Exercise
import com.personal.calisthenics.core.model.ExerciseKind
import com.personal.calisthenics.core.model.MovementCategory

/** Isometrics (Phase 1), strength work (Phase 2) and decompression drills (Phase 3). */
internal object ExerciseSeedMain {

    val all: List<Exercise> = listOf(
        Exercise(
            id = "l_sit",
            name = "Parallel Bar L-Sit / Tuck L-Sit",
            summary = "Support on parallel bars with the legs lifted in front; builds compression strength and shoulder depression.",
            category = MovementCategory.ISOMETRIC,
            kind = ExerciseKind.HOLD,
            highlights = listOf(
                muscle(HIP_FLEXORS, PRIMARY, END, "Hold the legs up against gravity"),
                muscle(ABS, PRIMARY, END, "Compress the trunk"),
                muscle(TRICEPS, SECONDARY, STEADY, "Lockout"),
                muscle(LOWER_TRAPS, PRIMARY, STEADY, "Scapular depression"),
                tendon(MEDIAL_ELBOW, SECONDARY, STEADY, "Locked-elbow loading"),
                joint(SHOULDER_JOINT, SECONDARY, STEADY),
            ),
            setupCues = listOf(
                "Grip the bars at hip level with straight arms and fully locked elbows.",
                "Push the shoulders down away from the ears (scapular depression).",
            ),
            executionCues = listOf(
                "Lift the knees (tuck) or extend the legs to horizontal (L-sit).",
                "Keep the legs together with the toes pointed and a posterior pelvic tilt.",
                "Hold 15-20 seconds and end the set as soon as form breaks.",
            ),
            jointProtection = "Static straight-arm loading of the elbows and shoulders with no momentum, ideal for tendon conditioning.",
            doDonts = listOf(
                DoDont(
                    title = "Shoulder position",
                    wrongLabel = "Shrugged shoulders, soft elbows",
                    wrongText = "Shoulders up near the ears and the elbows slightly bent.",
                    wrongConsequence = "The shoulder girdle collapses and overloads the AC joint.",
                    rightLabel = "Locked and depressed",
                    rightText = "Elbows locked, shoulders pressed down and the hips slightly in front of the bars.",
                    wrongPoseKey = "l_sit.wrong_shrugged",
                    rightPoseKey = "l_sit.right_depressed",
                ),
            ),
            ladder = listOf(
                level("Foot-Supported L-Sit", "Toes touch the floor or a box for help."),
                level("Tuck L-Sit", "Knees pulled toward the chest, feet off the floor."),
                level("One-Leg Extended L-Sit", "One leg extended, the other tucked."),
                level("Full L-Sit", "Both legs extended to horizontal."),
                level("Advanced L-Sit", "Legs held above horizontal."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "planche_lean",
            name = "Planche Lean",
            summary = "Straight-arm lean in a plank, shoulders pushed forward past the wrists, to condition wrists and the biceps tendon.",
            category = MovementCategory.ISOMETRIC,
            kind = ExerciseKind.HOLD,
            highlights = listOf(
                muscle(FRONT_DELT, PRIMARY, END),
                muscle(SERRATUS, PRIMARY, END),
                muscle(PECS, SECONDARY, END),
                tendon(DISTAL_BICEPS_TENDON, PRIMARY, END, "Straight-arm lengthened load"),
                joint(WRIST, PRIMARY, END, "Extension under load"),
                joint(SHOULDER_JOINT, SECONDARY, END),
            ),
            setupCues = listOf(
                "Start in a high plank with the hands turned out slightly and the elbows locked.",
                "Posterior pelvic tilt: tuck the tailbone under.",
            ),
            executionCues = listOf(
                "Protract the scapulae by pushing the floor away.",
                "Lean the shoulders forward past the wrists with straight arms.",
                "Hold 15-20 seconds and stop if the wrists or biceps tendon protest.",
            ),
            jointProtection = "The straight-arm lean is the main driver of biceps-tendon and wrist adaptation; increase the lean in small steps.",
            doDonts = listOf(
                DoDont(
                    title = "Body line",
                    wrongLabel = "Arched back, pinched shoulder blades",
                    wrongText = "Hips sagging, lower back arched and the shoulder blades squeezed together.",
                    wrongConsequence = "Dumps load into the lumbar spine and the front of the shoulder joint.",
                    rightLabel = "Tucked and protracted",
                    rightText = "Tailbone tucked, shoulder blades protracted, shoulders past the wrists.",
                    wrongPoseKey = "planche_lean.wrong_arched",
                    rightPoseKey = "planche_lean.right_tucked_protracted",
                ),
            ),
            ladder = listOf(
                level("Light Lean", "Shoulders just over the wrists."),
                level("Moderate Lean", "Shoulders about 5 cm past the wrists."),
                level("Deep Lean", "Shoulders 10 cm or more past the wrists."),
                level("Feet-Elevated Lean", "Feet raised on a low box."),
                level("Tuck Planche", "Feet lifted off the floor in a tuck."),
            ),
            startLevel = 0,
        ),
        Exercise(
            id = "strict_pullups",
            name = "Strict Pull-ups",
            summary = "Dead hang to chin over the bar with no kipping. The grip rotates by day: overhand, neutral, chin-up.",
            category = MovementCategory.PULL,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(LATS, PRIMARY, END),
                muscle(BICEPS, PRIMARY, END),
                muscle(LOWER_TRAPS, SECONDARY, STEADY),
                muscle(FOREARM_FLEXORS, SECONDARY, STEADY, "Grip"),
                tendon(DISTAL_BICEPS_TENDON, PRIMARY, START, "Peak load at the bottom"),
                tendon(MEDIAL_ELBOW, SECONDARY, STEADY, "Flexor origin under grip load"),
                joint(SHOULDER_JOINT, SECONDARY, START),
            ),
            setupCues = listOf(
                "Use an Active Hook Grip with the bar at the base of the fingers and the thumb wrapped.",
                "Start from a dead hang with the shoulders packed (down and back).",
            ),
            executionCues = listOf(
                "Tempo 3-1-X-0: lower for 3 seconds, pause 1 second in the hang, then drive up explosively.",
                "Pull the chest toward the bar, driving the elbows down and forward to the ribs.",
                "Rotate the grip by day (A overhand, B neutral, C chin-up) to spread tendon stress.",
            ),
            jointProtection = "Rotating grips across the week shifts load between the biceps tendon, brachialis and forearm flexors so no single tendon is overused.",
            doDonts = listOf(
                DoDont(
                    title = "Top position",
                    wrongLabel = "Shrugged shoulders, chin poke",
                    wrongText = "Shoulders up around the ears and the chin poking over the bar.",
                    wrongConsequence = "Skips the lats and jams the shoulder joint.",
                    rightLabel = "Chest to bar",
                    rightText = "Shoulders depressed, ribs down and the chest driven toward the bar.",
                    wrongPoseKey = "strict_pullups.wrong_shrug_chin_poke",
                    rightPoseKey = "strict_pullups.right_chest_to_bar",
                ),
                DoDont(
                    title = "Bar grip",
                    wrongLabel = "Bar deep in the palm crease",
                    wrongText = "Gripping the bar down in the crease of the palm.",
                    wrongConsequence = "Pinches the skin and rips calluses; the bar slides and the grip fatigues early.",
                    rightLabel = "Active Hook Grip",
                    rightText = "Bar at the base of the fingers with the thumb wrapped over.",
                    wrongPoseKey = "detail.grip_palm_crease",
                    rightPoseKey = "detail.grip_hook",
                ),
            ),
            ladder = listOf(
                level("Band-Assisted Pull-up", "Use a light band for assistance."),
                level("Strict Pull-up", "Full bodyweight, tempo 3-1-X-0."),
                level("Weighted Pull-up", "Add about 5 kg."),
                level("Archer Pull-up", "Pull toward one hand while the other arm extends."),
                level("Typewriter Pull-up", "Slide side to side at the top."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "parallel_bar_dips",
            name = "Parallel Bar Dips",
            summary = "Controlled dips on parallel bars with a slight forward lean, stopping at parallel.",
            category = MovementCategory.PUSH,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(PECS, PRIMARY, END),
                muscle(TRICEPS, PRIMARY, STEADY),
                muscle(FRONT_DELT, SECONDARY, END),
                tendon(MEDIAL_ELBOW, SECONDARY, END, "Elbow tendons under tension"),
                joint(SHOULDER_JOINT, PRIMARY, END, "Anterior capsule at the bottom"),
            ),
            setupCues = listOf(
                "Start in a straight-arm support with the elbows locked and the shoulders depressed.",
                "Lean slightly forward with the legs bent behind you.",
            ),
            executionCues = listOf(
                "Tempo 3-0-1-0: lower for 3 seconds with the elbows traveling back at about 45 degrees.",
                "Stop when the upper arms are parallel to the floor.",
                "Press up and finish with fully locked elbows and depressed shoulders.",
            ),
            jointProtection = "Controlled depth protects the anterior shoulder capsule and the biceps tendon from over-stretch.",
            doDonts = listOf(
                DoDont(
                    title = "Depth and elbows",
                    wrongLabel = "Too deep, flared elbows",
                    wrongText = "Sinking below parallel with flared elbows and rounded shoulders.",
                    wrongConsequence = "Over-extends the anterior shoulder capsule and invites impingement.",
                    rightLabel = "Parallel, elbows back",
                    rightText = "Chest forward, elbows about 45 degrees back, stop at parallel.",
                    wrongPoseKey = "parallel_bar_dips.wrong_deep_flared",
                    rightPoseKey = "parallel_bar_dips.right_parallel",
                ),
            ),
            ladder = listOf(
                level("Bench Dips", "Hands on a bench behind you, feet on the floor."),
                level("Negative Dips", "Slow lowering, step up to return."),
                level("Parallel Bar Dips", "Full bodyweight, tempo 3-0-1-0."),
                level("Weighted Dips", "Add about 5 kg."),
                level("Russian Dips", "Dip down and forward to the forearms."),
            ),
            startLevel = 2,
        ),
        Exercise(
            id = "straight_bar_dips",
            name = "Straight Bar Dips",
            summary = "Dips over a single bar: chest over the bar, elbows close, ribs down.",
            category = MovementCategory.PUSH,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(PECS, PRIMARY, END),
                muscle(TRICEPS, PRIMARY, STEADY),
                muscle(FRONT_DELT, SECONDARY, END),
                joint(WRIST, SECONDARY, STEADY, "Bar sits at the base of the palm"),
                joint(SHOULDER_JOINT, SECONDARY, END),
            ),
            setupCues = listOf(
                "Grip the bar at the base of the palm with the thumbs wrapped and jump to support with locked elbows.",
                "Lean the chest forward over the bar with the legs behind.",
            ),
            executionCues = listOf(
                "Use the same tempo as parallel dips (3-0-1-0).",
                "Lower the chest toward the bar with the elbows traveling back and the forearms roughly vertical.",
                "Press to full lockout and depress the shoulders.",
            ),
            jointProtection = "The straight bar demands wrist extension; this variation changes the wrist angle versus parallel bars to spread joint stress.",
            doDonts = listOf(
                DoDont(
                    title = "Chest position",
                    wrongLabel = "Chest behind the bar",
                    wrongText = "Staying upright with the forearms angled back.",
                    wrongConsequence = "Moves the load to the front of the shoulder and the wrists.",
                    rightLabel = "Chest over the bar",
                    rightText = "Forearms vertical, chest over the bar, elbows close.",
                    wrongPoseKey = "straight_bar_dips.wrong_upright",
                    rightPoseKey = "straight_bar_dips.right_chest_over",
                ),
            ),
            ladder = listOf(
                level("Straight Bar Support Hold", "Static support with locked elbows."),
                level("Negative Straight Bar Dips", "Slow lowering, step up to return."),
                level("Straight Bar Dips", "Full bodyweight, tempo 3-0-1-0."),
                level("Weighted Straight Bar Dips", "Add about 5 kg."),
            ),
            startLevel = 2,
        ),
        Exercise(
            id = "australian_pullups",
            name = "Elevated Australian Pull-ups (Bodyweight Rows)",
            summary = "Horizontal row under a low bar with the feet elevated; builds the mid-back with joint-friendly elbow angles.",
            category = MovementCategory.PULL,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(MID_BACK, PRIMARY, END),
                muscle(LATS, PRIMARY, END),
                muscle(REAR_DELT, SECONDARY, END),
                muscle(BICEPS, SECONDARY, END),
                tendon(DISTAL_BICEPS_TENDON, SECONDARY, START),
                joint(SHOULDER_JOINT, MINOR, STEADY),
            ),
            setupCues = listOf(
                "Set the bar at about hip height and place the heels on a bench or step.",
                "Keep the body in a straight line from head to heels.",
            ),
            executionCues = listOf(
                "Tempo 2-0-1-1: lower for 2 seconds, drive up for 1 second and squeeze the chest to the bar for 1 second.",
                "Retract the shoulder blades first, then bend the elbows.",
                "Keep the glutes squeezed and the ribs down.",
            ),
            jointProtection = "Horizontal pulling spares the elbow-flexor tendon compared with heavy vertical pulls while still building the scapular retractors.",
            doDonts = listOf(
                DoDont(
                    title = "Body line",
                    wrongLabel = "Hips sagging, head reaching",
                    wrongText = "The hips drop and the neck reaches for the bar.",
                    wrongConsequence = "The lumbar spine bears the load and the row range shortens.",
                    rightLabel = "Rigid plank line",
                    rightText = "Glutes tight, ribs down, pull the chest to the bar.",
                    wrongPoseKey = "australian_pullups.wrong_sagging",
                    rightPoseKey = "australian_pullups.right_plank_line",
                ),
            ),
            ladder = listOf(
                level("High-Bar Row", "Bar high, body more upright (easier)."),
                level("Mid-Bar Row", "Bar at waist height, feet on the floor."),
                level("Feet-Elevated Row", "Heels on a bench, bar at hip height."),
                level("Archer Row", "Pull toward one hand while the other arm extends."),
                level("One-Arm Row", "Single-arm row with a stable hold."),
            ),
            startLevel = 2,
        ),
        Exercise(
            id = "pike_pushups",
            name = "Pike Push-ups",
            summary = "Vertical pressing from an inverted V; head travels in front of the hands in a tripod path.",
            category = MovementCategory.PUSH,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(FRONT_DELT, PRIMARY, END),
                muscle(TRICEPS, SECONDARY, STEADY),
                muscle(SERRATUS, SECONDARY, START),
                joint(SHOULDER_JOINT, PRIMARY, END, "Impingement risk if elbows flare"),
                joint(WRIST, SECONDARY, STEADY),
            ),
            setupCues = listOf(
                "Start in an inverted V with the hips high, the hands shoulder-width apart and the arms straight.",
                "Walk the feet in until the shoulders stack over the hands.",
            ),
            executionCues = listOf(
                "Tempo 3-1-1-0: lower the head toward a point just in front of the hands for 3 seconds.",
                "Head and hands form an equilateral triangle (tripod).",
                "Keep the elbows about 45 degrees from the ribs and press up to a full shoulder shrug at the top.",
            ),
            jointProtection = "The tripod path keeps the humerus in the scapular plane, avoiding shoulder impingement.",
            doDonts = listOf(
                DoDont(
                    title = "Head and elbow path",
                    wrongLabel = "Flared elbows, head between the hands",
                    wrongText = "Elbows flaring wide while the head drops between the hands.",
                    wrongConsequence = "Shoulder impingement: the humerus jams under the acromion.",
                    rightLabel = "Equilateral tripod",
                    rightText = "Lean forward so the head and hands form an equilateral triangle.",
                    wrongPoseKey = "pike_pushups.wrong_flare_head_between",
                    rightPoseKey = "pike_pushups.right_tripod",
                ),
            ),
            ladder = listOf(
                level("Ground Pike Push-up", "Feet on the floor, hips high."),
                level("Elevated Pike Push-up", "Feet elevated on a bench."),
                level("High Feet-Elevated Pike Push-up", "Feet on a higher surface, near-vertical torso."),
                level("Wall Handstand Negative", "Kick up and lower slowly in front of a wall."),
                level("Wall Handstand Push-up", "Full range push-up against the wall."),
            ),
            startLevel = 0,
        ),
        Exercise(
            id = "pseudo_planche_pushups",
            name = "Pseudo Planche Push-ups",
            summary = "Push-ups with the hands level with the waist and the shoulders far ahead of them; elbows tucked to the ribs.",
            category = MovementCategory.PUSH,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(FRONT_DELT, PRIMARY, END),
                muscle(PECS, PRIMARY, END),
                muscle(TRICEPS, SECONDARY, STEADY),
                tendon(DISTAL_BICEPS_TENDON, SECONDARY, START, "Lengthened under lean"),
                joint(WRIST, PRIMARY, STEADY),
                joint(SHOULDER_JOINT, SECONDARY, END),
            ),
            setupCues = listOf(
                "Start in a plank with the hands turned out slightly and level with the lower ribs or waist.",
                "Lean the shoulders forward past the hands and tuck the pelvis.",
            ),
            executionCues = listOf(
                "Tempo 3-1-1-0 with the elbows tucked tight to the ribs.",
                "Keep the forward lean constant throughout the rep.",
                "Stop the set when the lean or the pelvic tuck fades.",
            ),
            jointProtection = "Bent-arm planche leans load the wrists and the biceps tendon; progress the lean slowly.",
            doDonts = listOf(
                DoDont(
                    title = "Hand and shoulder position",
                    wrongLabel = "Hands under the chest, no lean",
                    wrongText = "Hands placed near the chest with the shoulders stacked over them.",
                    wrongConsequence = "It becomes an ordinary push-up and misses the planche angle.",
                    rightLabel = "Hands at the waist, shoulders ahead",
                    rightText = "Hands level with the waist, shoulders past the hands, elbows tucked.",
                    wrongPoseKey = "pseudo_planche_pushups.wrong_no_lean",
                    rightPoseKey = "pseudo_planche_pushups.right_leaning",
                ),
            ),
            ladder = listOf(
                level("Pseudo Planche Push-up, Light Lean", "Shoulders slightly ahead of the hands."),
                level("Pseudo Planche Push-up, Deep Lean", "Shoulders well ahead of the hands."),
                level("Pseudo Planche Push-up, Feet Elevated", "Feet on a low box."),
                level("Tuck Planche Push-up Negative", "Slow lowering from a tuck planche."),
                level("Tuck Planche Push-up", "Full range from a tuck planche."),
            ),
            startLevel = 0,
        ),
        Exercise(
            id = "pistol_squat",
            name = "Pistol Squat Progression / Bulgarian Split Squat",
            summary = "Single-leg squat strength with slow eccentrics to condition the patellar and Achilles tendons.",
            category = MovementCategory.LEGS,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(QUADS, PRIMARY, END),
                muscle(GLUTES, PRIMARY, END),
                tendon(PATELLAR_TENDON, PRIMARY, END, "Loaded eccentrically, peak at the bottom"),
                tendon(ACHILLES, SECONDARY, END),
                joint(KNEE_JOINT, PRIMARY, END),
                joint(ANKLE_JOINT, SECONDARY, END),
            ),
            setupCues = listOf(
                "Bulgarian split squat: rear foot on a bench behind you, front foot far enough forward for a vertical shin.",
                "Pistol: stand on one leg with the other leg extended in front and the arms reaching forward.",
            ),
            executionCues = listOf(
                "Tempo 3-1-1-0: lower for 3 seconds, pause 1 second at the bottom, then drive up.",
                "The knee tracks over the middle toes and the heel stays glued to the floor.",
                "Complete 6-8 reps per leg with 60 seconds of rest between legs.",
            ),
            jointProtection = "Slow eccentric single-leg work is one of the safest ways to build the patellar and Achilles tendons.",
            doDonts = listOf(
                DoDont(
                    title = "Knee tracking",
                    wrongLabel = "Knee caving, heel lifting",
                    wrongText = "The knee collapses inward and the heel peels off the floor.",
                    wrongConsequence = "Valgus knee stresses the patellar tendon and the medial knee ligaments.",
                    rightLabel = "Knee over middle toes",
                    rightText = "Heel down, hips back, knee tracking over the middle toes.",
                    wrongPoseKey = "pistol_squat.wrong_valgus",
                    rightPoseKey = "pistol_squat.right_tracking",
                ),
            ),
            ladder = listOf(
                level("Bulgarian Split Squat", "Rear foot on a bench."),
                level("Elevated Bulgarian Split Squat", "Front foot on a small plate."),
                level("Box Pistol Squat", "Sit back to a box and stand up on one leg."),
                level("Assisted Pistol Squat", "Hold a pole or band for balance."),
                level("Pistol Squat", "Full bodyweight, unassisted."),
                level("Weighted Pistol Squat", "Add a small counterweight."),
            ),
            startLevel = 0,
        ),
        Exercise(
            id = "nordic_curl",
            name = "Assisted Nordic Hamstring Curls / Single-Leg Hip Thrust",
            summary = "Long-lever eccentric hamstring work with hand assistance; hip thrust is the regression.",
            category = MovementCategory.LEGS,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(HAMSTRINGS, PRIMARY, END),
                muscle(GLUTES, SECONDARY, END),
                tendon(HAMSTRING_TENDON, PRIMARY, END, "Eccentric tendon loading"),
                joint(KNEE_JOINT, SECONDARY, END),
            ),
            setupCues = listOf(
                "Kneel on a pad with the ankles anchored under a sturdy bar or held by a partner.",
                "Keep a band or pole in reach for assistance if needed.",
            ),
            executionCues = listOf(
                "Tempo 4-0-1-0: lower for 4 seconds keeping a straight line from the knees to the head.",
                "Catch yourself with the hands and push back to the start.",
                "Hip-thrust regression: shoulders on a bench, one leg driving, hips level.",
            ),
            jointProtection = "Long-lever eccentric work is the best-evidenced way to condition the hamstring tendons.",
            doDonts = listOf(
                DoDont(
                    title = "Hip position",
                    wrongLabel = "Breaking at the hips",
                    wrongText = "The hips fold backward as the torso drops.",
                    wrongConsequence = "Takes the load off the hamstrings and removes the stimulus.",
                    rightLabel = "Straight line",
                    rightText = "Hips extended, a straight line from the knees to the head.",
                    wrongPoseKey = "nordic_curl.wrong_hip_pike",
                    rightPoseKey = "nordic_curl.right_straight_line",
                ),
            ),
            ladder = listOf(
                level("Single-Leg Hip Thrust", "Bench-supported hip extension on one leg."),
                level("Banded Nordic Curl", "A band overhead supplies assistance."),
                level("Assisted Nordic Curl", "Hands catch you at the bottom."),
                level("Slow Nordic Negative", "5 second controlled lowering."),
                level("Full Nordic Curl", "Lower and return with the hamstrings."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "hanging_leg_raises",
            name = "Hanging Leg Raises / Toes-to-Bar",
            summary = "Strict hanging core work with a pelvic tuck and slow lowering; zero momentum.",
            category = MovementCategory.CORE,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(ABS, PRIMARY, END),
                muscle(HIP_FLEXORS, PRIMARY, END),
                muscle(LATS, SECONDARY, STEADY, "Stabilizes the hang"),
                muscle(FOREARM_FLEXORS, SECONDARY, STEADY, "Grip"),
                tendon(MEDIAL_ELBOW, SECONDARY, STEADY, "Grip load"),
                joint(SHOULDER_JOINT, SECONDARY, STEADY),
            ),
            setupCues = listOf(
                "Hang with an active hook grip and the shoulders packed.",
                "Tuck the pelvis (posterior tilt) before you lift.",
            ),
            executionCues = listOf(
                "Tempo 3-0-1-0: lift the legs with the pelvic tuck and lower them for 3 seconds.",
                "Use zero momentum and no swinging.",
                "Raise to 90 degrees first; go to toes-to-bar once the swing is gone.",
            ),
            jointProtection = "Strict lowering avoids sudden shoulder traction and shock loading of the hip-flexor tendons.",
            doDonts = listOf(
                DoDont(
                    title = "Momentum",
                    wrongLabel = "Swinging and arching",
                    wrongText = "Arching the back and swinging to create momentum.",
                    wrongConsequence = "Shock-loads the shoulders and strips the abs of the work.",
                    rightLabel = "Strict and tucked",
                    rightText = "Pelvic tuck, controlled lift and a 3 second lowering.",
                    wrongPoseKey = "hanging_leg_raises.wrong_swing",
                    rightPoseKey = "hanging_leg_raises.right_strict",
                ),
            ),
            ladder = listOf(
                level("Hanging Knee Raise", "Knees to chest."),
                level("Hanging Leg Raise to 90", "Straight legs to horizontal."),
                level("Toes-to-Bar", "Toes touch the bar."),
                level("Weighted Toes-to-Bar", "Hold a light weight between the feet."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "german_hang",
            name = "German Hang Progression (Feet-Assisted Skin the Cat)",
            summary = "Loaded stretch for the front of the shoulder and the distal biceps tendon, assisted by the feet on a low bar.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.HOLD,
            highlights = listOf(
                muscle(FRONT_DELT, PRIMARY, END, "Anterior deltoid stretch"),
                muscle(PEC_MINOR, SECONDARY, END, "Lengthened"),
                tendon(DISTAL_BICEPS_TENDON, SECONDARY, END, "Lengthened under gentle load"),
                joint(SHOULDER_JOINT, PRIMARY, END, "End-range extension"),
            ),
            setupCues = listOf(
                "Use a low bar with the feet on the floor or a box to assist.",
                "Grip with a hook grip.",
            ),
            executionCues = listOf(
                "Roll back through the bar slowly while keeping the shoulders active.",
                "Hold 30 seconds per set only in a comfortable stretch.",
                "Exit by lowering the feet to the floor under control.",
            ),
            jointProtection = "Stretches the anterior shoulder structures and loads the distal biceps tendon gently in its lengthened position.",
            doDonts = listOf(
                DoDont(
                    title = "Shoulder control",
                    wrongLabel = "Dropping into end range passively",
                    wrongText = "Dropping into full depth with shrugged, passive shoulders.",
                    wrongConsequence = "Overstretches the anterior capsule and the long head of the biceps.",
                    rightLabel = "Feet-assisted depth",
                    rightText = "Work to a comfortable depth with active shoulders.",
                    wrongPoseKey = "german_hang.wrong_passive_drop",
                    rightPoseKey = "german_hang.right_feet_assisted",
                ),
            ),
            ladder = listOf(
                level("Feet-Assisted German Hang", "Feet on a low box."),
                level("Tuck German Hang", "Knees tucked, hips high."),
                level("Straight-Body German Hang", "Straight body hang behind the bar."),
                level("Skin-the-Cat Rolls", "Controlled rolls through the full range."),
            ),
            startLevel = 0,
        ),
        Exercise(
            id = "forearm_flexor_extensor_stretch",
            name = "Locked-Elbow Forearm Flexor & Extensor Stretch",
            summary = "Gentle locked-elbow stretches for the forearm flexors and extensors; direct golfer's-elbow prevention.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.HOLD,
            highlights = listOf(
                muscle(FOREARM_EXTENSORS, PRIMARY, START, "Stretched while the fingers point down"),
                muscle(FOREARM_FLEXORS, PRIMARY, END, "Stretched while the fingers point up"),
                tendon(LATERAL_ELBOW, SECONDARY, START, "Extensor tendon origin"),
                tendon(MEDIAL_ELBOW, SECONDARY, END, "Flexor tendon origin"),
                joint(WRIST, SECONDARY, STEADY),
            ),
            setupCues = listOf(
                "Extend one arm in front with the elbow locked, palm up for the flexors or palm down for the extensors.",
                "Use the other hand to draw the fingers back gently.",
            ),
            executionCues = listOf(
                "Hold 30 seconds per side and direction.",
                "Keep the elbow locked and the shoulder down.",
                "Breathe slowly and keep the stretch at a mild pull.",
            ),
            jointProtection = "Lengthens the flexor tendon origin without overloading it, which is the direct prevention for golfer's elbow.",
            doDonts = listOf(
                DoDont(
                    title = "Elbow and pressure",
                    wrongLabel = "Bent elbow, hard yank",
                    wrongText = "A bent elbow and a hard pull on the fingers.",
                    wrongConsequence = "Sudden loading of the tendon origin risks irritation.",
                    rightLabel = "Locked elbow, gentle pressure",
                    rightText = "Elbow locked with steady, gentle pressure.",
                    wrongPoseKey = "forearm_flexor_extensor_stretch.wrong_yank",
                    rightPoseKey = "forearm_flexor_extensor_stretch.right_gentle",
                ),
            ),
            ladder = listOf(
                level("Gentle Wall Stretch", "Palm on a wall, rotate the body away."),
                level("Standing Locked-Elbow Stretch", "Standing, hand-assisted stretch."),
                level("Quadruped Palm Stretch", "Hands on the floor, lean gently."),
                level("Held Extension Stretch", "Hold at the end of the range for longer."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "prying_deep_squat",
            name = "Prying Deep Squat Hold",
            summary = "A deep squat hold with the elbows prying the knees apart to mobilize the ankles and hips.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.HOLD,
            highlights = listOf(
                muscle(GLUTES, SECONDARY, END),
                muscle(QUADS, SECONDARY, END),
                tendon(ACHILLES, SECONDARY, END, "Ankle dorsiflexion stretch"),
                tendon(PATELLAR_TENDON, MINOR, END, "Low-force lengthened loading"),
                joint(ANKLE_JOINT, PRIMARY, END),
                joint(HIP_JOINT, PRIMARY, END),
            ),
            setupCues = listOf(
                "Stand with the feet slightly wider than the shoulders and the toes out about 30 degrees.",
                "Hold a post or counterbalance if needed.",
            ),
            executionCues = listOf(
                "Sink into the deepest comfortable squat with the heels flat.",
                "Press the elbows into the inner knees (pry) to open the hips.",
                "Hold 90 seconds continuous, shifting gently side to side, and breathe.",
            ),
            jointProtection = "Mobilizes ankle dorsiflexion and loads the Achilles and patellar tendons in a lengthened, low-force position.",
            doDonts = listOf(
                DoDont(
                    title = "Heels and knees",
                    wrongLabel = "Heels lifting, knees caving",
                    wrongText = "The heels peel up and the knees fall inward.",
                    wrongConsequence = "Unloads the Achilles but crushes the medial knee.",
                    rightLabel = "Heels flat, knees out",
                    rightText = "Heels flat, knees tracking over the toes and the elbows prying.",
                    wrongPoseKey = "prying_deep_squat.wrong_heels_up",
                    rightPoseKey = "prying_deep_squat.right_heels_down",
                ),
            ),
            ladder = listOf(
                level("Supported Deep Squat", "Hold a post for balance."),
                level("Heels-Elevated Deep Squat", "Small plate under the heels."),
                level("Flat-Heel Deep Squat", "Unsupported, heels down."),
                level("Weighted Prying Squat", "Hold a light counterweight at the chest."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "jefferson_curl",
            name = "Bodyweight Jefferson Curl (off a Bench)",
            summary = "Slow, light spinal flexion standing on a bench to lengthen the hamstrings and the thoracolumbar fascia.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.HOLD,
            highlights = listOf(
                muscle(HAMSTRINGS, PRIMARY, END),
                muscle(ERECTORS, PRIMARY, END, "Lengthened, not loaded"),
                tendon(HAMSTRING_TENDON, SECONDARY, END, "Lengthened under bodyweight"),
                tendon(THORACOLUMBAR, SECONDARY, END, "Fascial tension"),
            ),
            setupCues = listOf(
                "Stand on a bench with the toes at the edge and soft knees.",
                "Tuck the chin to the chest and let the arms hang.",
            ),
            executionCues = listOf(
                "Roll down one vertebra at a time, head first.",
                "Move slowly for about 30 seconds per set with no added weight.",
                "Reverse slowly, stacking the spine from the pelvis upward.",
            ),
            jointProtection = "Lengthens the hamstrings and thoracolumbar fascia under pure bodyweight tension.",
            doDonts = listOf(
                DoDont(
                    title = "Speed and load",
                    wrongLabel = "Fast and bouncing",
                    wrongText = "Dropping quickly and bouncing at the bottom.",
                    wrongConsequence = "Loaded spinal flexion at speed can overload the discs.",
                    rightLabel = "Slow, vertebra by vertebra",
                    rightText = "Light, slow and segmental from the head down.",
                    wrongPoseKey = "jefferson_curl.wrong_fast_bounce",
                    rightPoseKey = "jefferson_curl.right_segmental",
                ),
            ),
            ladder = listOf(
                level("Standing Jefferson Curl", "Floor level, no bench."),
                level("Bench Jefferson Curl", "Standing on a bench with bodyweight only."),
                level("Bench Jefferson Curl, 2 kg", "Add a light 2 kg weight."),
                level("Bench Jefferson Curl, 5 kg", "Add a 5 kg weight."),
            ),
            startLevel = 1,
        ),
    )
}
