package com.personal.calisthenics.core.seed

import com.personal.calisthenics.core.model.BodyRegion.*
import com.personal.calisthenics.core.model.Load.*
import com.personal.calisthenics.core.model.PeakAt.*
import com.personal.calisthenics.core.model.DoDont
import com.personal.calisthenics.core.model.Exercise
import com.personal.calisthenics.core.model.ExerciseKind
import com.personal.calisthenics.core.model.MovementCategory

/** Warm-up, wrist prep and scapular / elbow activation drills (Phase 0). */
internal object ExerciseSeedPrep {

    val all: List<Exercise> = listOf(
        Exercise(
            id = "jumping_jacks",
            name = "Jumping Jacks",
            summary = "Raises core temperature and takes the shoulders through full overhead range before any joint-loading work.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(CALVES, PRIMARY, STEADY, "Springy ankle work"),
                joint(SHOULDER_JOINT, SECONDARY, END, "Full overhead range"),
                tendon(ACHILLES, MINOR, STEADY, "Light elastic loading"),
            ),
            setupCues = listOf(
                "Stand tall with feet together and arms at your sides.",
                "Keep the ribs stacked over the pelvis.",
            ),
            executionCues = listOf(
                "Jump the feet wide as both arms sweep overhead.",
                "Land softly on the balls of the feet, heels just kissing the floor.",
                "Keep a steady rhythm and smooth nasal breathing.",
            ),
            jointProtection = "Warms the Achilles and patellar tendons with low-amplitude bounces so they are elastic before loaded work.",
            doDonts = listOf(
                DoDont(
                    title = "Landing mechanics",
                    wrongLabel = "Stiff-legged heel slap",
                    wrongText = "Locked knees and heels slamming into the floor.",
                    wrongConsequence = "Shock travels straight into the patellar and Achilles tendons.",
                    rightLabel = "Soft quarter-squat landing",
                    rightText = "Land on the balls of the feet with soft knees tracking over the toes.",
                    wrongPoseKey = "jumping_jacks.wrong_stiff_landing",
                    rightPoseKey = "jumping_jacks.right_soft_landing",
                ),
            ),
            ladder = listOf(
                level("Step Jacks", "Low impact: step the feet out one at a time."),
                level("Jumping Jacks", "Standard jumping jack at a steady pace."),
                level("Squat Jacks", "Jump wide into a quarter squat with hands at the chest."),
                level("Skater Hops", "Lateral single-leg landings to build tendon stiffness."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "joint_circles",
            name = "Neck, Shoulder, Elbow, Hip & Ankle Circles",
            summary = "Slow, smooth circles that lubricate each joint through its comfortable range before loading.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(REAR_DELT, MINOR, STEADY, "Gentle rotator-cuff activation"),
                joint(SHOULDER_JOINT, PRIMARY, STEADY, "Capsule lubrication"),
                joint(HIP_JOINT, SECONDARY, STEADY, "Hip capsule"),
                joint(ANKLE_JOINT, SECONDARY, STEADY, "Ankle mobility"),
                tendon(MEDIAL_ELBOW, MINOR, STEADY, "Elbow circles prime the flexor origin"),
            ),
            setupCues = listOf(
                "Stand tall with soft knees.",
                "Work from the neck down: about 5 slow circles each way per joint.",
            ),
            executionCues = listOf(
                "Make each circle as large as is comfortable without forcing end range.",
                "Keep the rest of the body quiet.",
                "Neck: use half circles (ear to shoulder, chin to chest) and never roll the head back.",
            ),
            jointProtection = "Distributes synovial fluid ahead of loading; the elbow circles specifically prime the medial elbow.",
            doDonts = listOf(
                DoDont(
                    title = "Neck circles",
                    wrongLabel = "Full backward head roll",
                    wrongText = "Dropping the head back and rolling through hyperextension.",
                    wrongConsequence = "Crunches the cervical facet joints and can irritate nerve roots.",
                    rightLabel = "Half circles, long neck",
                    rightText = "Chin to chest, ear to shoulder; keep the neck long and relaxed.",
                    wrongPoseKey = "joint_circles.wrong_neck_hyperextend",
                    rightPoseKey = "joint_circles.right_neck_neutral",
                ),
            ),
            ladder = listOf(
                level("Small Circles", "Half range, very gentle."),
                level("Full Circles", "Largest comfortable range."),
                level("Loaded Circles", "Hold a light band or a 1-2 kg plate."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "banded_dislocates",
            name = "Banded Shoulder Dislocates",
            summary = "Overhead-to-behind sweep of a band with straight arms to open the shoulder capsule.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                joint(SHOULDER_JOINT, PRIMARY, STEADY, "Capsule mobility"),
                muscle(REAR_DELT, SECONDARY, END),
                muscle(LOWER_TRAPS, SECONDARY, END),
            ),
            setupCues = listOf(
                "Hold a light band with a wide grip, thumbs facing each other.",
                "Ribs down, glutes lightly squeezed, no low-back arch.",
            ),
            executionCues = listOf(
                "Keep the elbows locked straight throughout.",
                "Sweep the band slowly overhead and behind the hips, then return.",
                "Narrow the grip only when you can pass without the ribs flaring or the elbows bending.",
            ),
            jointProtection = "Adds overhead and extension range so the shoulder blade can rotate freely in pull-ups and dips.",
            doDonts = listOf(
                DoDont(
                    title = "Rib position",
                    wrongLabel = "Ribs flared, elbows bent",
                    wrongText = "Arched low back, flared ribs and bent elbows to get the band around.",
                    wrongConsequence = "The range is borrowed from the lumbar spine instead of the shoulder.",
                    rightLabel = "Ribs down, arms straight",
                    rightText = "Ribs stacked, elbows locked, grip wide enough to pass smoothly.",
                    wrongPoseKey = "banded_dislocates.wrong_ribs_flared",
                    rightPoseKey = "banded_dislocates.right_ribs_down",
                ),
            ),
            ladder = listOf(
                level("Very Wide Grip", "Very wide grip, easy pass."),
                level("Medium Grip", "Gradually narrower grip, 20 reps."),
                level("Narrow Grip", "Shoulder-width plus a little; strict elbows."),
                level("Rigid Stick", "Pass a stick or dowel with straight arms."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "band_pull_aparts",
            name = "Band Pull-Aparts",
            summary = "Activates the rear delts and mid-back that hold the shoulder blades in place during pulling.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(REAR_DELT, PRIMARY, END),
                muscle(MID_BACK, PRIMARY, END),
                muscle(LOWER_TRAPS, SECONDARY, END),
                joint(SHOULDER_JOINT, MINOR, STEADY),
            ),
            setupCues = listOf(
                "Hold a light band at shoulder height, hands shoulder-width apart, arms straight.",
                "Stand tall with the ribs down.",
            ),
            executionCues = listOf(
                "Pull the band apart by squeezing the shoulder blades together and back.",
                "Keep the shoulders down rather than shrugged.",
                "Control the return and keep tension on the band.",
            ),
            jointProtection = "Strengthens the scapular retractors that share load with the biceps and elbow flexors during pulling.",
            doDonts = listOf(
                DoDont(
                    title = "Shoulder position",
                    wrongLabel = "Shrugged and arched",
                    wrongText = "Shoulders up near the ears and the back arched.",
                    wrongConsequence = "The upper traps take over and the shoulder blades never set.",
                    rightLabel = "Shoulders down, chest tall",
                    rightText = "Shoulders pressed down; pull from the shoulder blades.",
                    wrongPoseKey = "band_pull_aparts.wrong_shrug",
                    rightPoseKey = "band_pull_aparts.right_depressed",
                ),
            ),
            ladder = listOf(
                level("Light Band", "Easy resistance, 20 clean reps."),
                level("Medium Band", "Standard warm-up resistance."),
                level("Heavy Band", "Strong resistance with strict form."),
                level("2-Second Hold", "Hold the end position for 2 seconds each rep."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "first_knuckle_raises",
            name = "First Knuckle Raises / Palm Pulses",
            summary = "Kneeling wrist prep: lift the palm heels off the floor and lower them with control.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(FOREARM_FLEXORS, PRIMARY, END, "Finger flexors do the lifting"),
                tendon(MEDIAL_ELBOW, SECONDARY, STEADY, "Common flexor origin"),
                joint(WRIST, SECONDARY, END, "Capsule conditioning"),
            ),
            setupCues = listOf(
                "Kneel on all fours with the hands under the shoulders and the fingers spread forward.",
                "Lock the elbows straight.",
            ),
            executionCues = listOf(
                "Press the fingertips into the floor and roll the palm heels up toward the first knuckles.",
                "Lower under control; do not let the palm slam down.",
                "Complete 15 smooth, pain-free reps.",
            ),
            jointProtection = "Gradually conditions the finger flexors and the wrist capsule; connective tissue adapts far more slowly than muscle.",
            doDonts = listOf(
                DoDont(
                    title = "Elbow position",
                    wrongLabel = "Soft, bent elbows",
                    wrongText = "Bending the elbows and rocking the whole body.",
                    wrongConsequence = "It turns into a push-up and removes the wrist load you are trying to build.",
                    rightLabel = "Locked elbows",
                    rightText = "All movement comes from the fingers and wrists only.",
                    wrongPoseKey = "first_knuckle_raises.wrong_bent_elbows",
                    rightPoseKey = "first_knuckle_raises.right_locked",
                ),
            ),
            ladder = listOf(
                level("Knees Down, Light Load", "Hands under the shoulders."),
                level("Hands Under Hips", "Slightly more load on the wrists."),
                level("Plank Position", "Full bodyweight bias."),
                level("Fingertip Plank", "Highest finger-flexor demand."),
            ),
            startLevel = 0,
        ),
        Exercise(
            id = "wrist_extensor_leans",
            name = "Forward Wrist Extensor Leans",
            summary = "Palms flat, elbows locked: lean the shoulders forward over the wrists and hold for 2 seconds.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(FOREARM_EXTENSORS, SECONDARY, STEADY, "Stabilise the wrist"),
                muscle(FOREARM_FLEXORS, SECONDARY, END, "Lengthened as you lean"),
                tendon(LATERAL_ELBOW, SECONDARY, STEADY, "Common extensor origin"),
                joint(WRIST, PRIMARY, END, "Wrist extension range"),
            ),
            setupCues = listOf(
                "Kneel with the palms flat and the fingers pointing forward.",
                "Lock the elbows and start with the shoulders directly over the wrists.",
            ),
            executionCues = listOf(
                "Shift the shoulders forward past the wrists until you feel a mild stretch.",
                "Hold for 2 seconds, then rock back.",
                "Do 10 reps and stop short of any pain at the wrist crease.",
            ),
            jointProtection = "Builds the wrist-extension range that straight-arm work such as planche leans and push-ups demands.",
            doDonts = listOf(
                DoDont(
                    title = "Palm contact",
                    wrongLabel = "Palm heels peeling off",
                    wrongText = "Lifting the heel of the hand as you lean forward.",
                    wrongConsequence = "Concentrates load on the wrist crease and removes the stretch.",
                    rightLabel = "Whole palm flat",
                    rightText = "Even pressure through the knuckles and palm heel.",
                    wrongPoseKey = "wrist_extensor_leans.wrong_palm_lifting",
                    rightPoseKey = "wrist_extensor_leans.right_flat_palm",
                ),
            ),
            ladder = listOf(
                level("Fingers Forward", "Standard lean with the fingers pointing forward."),
                level("Fingers Turned Out 45", "Fingers rotated out about 45 degrees."),
                level("Fingers Turned Out 90", "Fingers pointing out to the sides."),
                level("Fingers Pointing Back", "Planche-style hand position."),
            ),
            startLevel = 0,
        ),
        Exercise(
            id = "palms_back_flexor_stretch",
            name = "Palms-Back Flexor Stretch",
            summary = "Fingers pointing back toward the knees; slowly rock the hips toward the heels.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(FOREARM_FLEXORS, PRIMARY, END),
                tendon(MEDIAL_ELBOW, SECONDARY, END, "Golfer's elbow origin"),
                joint(WRIST, PRIMARY, END),
            ),
            setupCues = listOf(
                "Kneel and place the palms down with the fingers pointing back toward your knees.",
                "Keep the elbows locked and the palms flat.",
            ),
            executionCues = listOf(
                "Rock the hips slowly toward the heels for 10 slow pulses.",
                "Stay in a mild stretch, never a sharp one.",
                "Breathe out as you rock back.",
            ),
            jointProtection = "Lengthens the forearm flexors and the common flexor tendon, the golfer's-elbow site.",
            doDonts = listOf(
                DoDont(
                    title = "Stretch intensity",
                    wrongLabel = "Forced and bouncing",
                    wrongText = "Bent elbows, sudden bounces and aggressive hip drops.",
                    wrongConsequence = "Overstretches the wrist ligaments and strains the flexor tendon.",
                    rightLabel = "Slow pulses",
                    rightText = "Locked elbows and slow pulses within a mild stretch.",
                    wrongPoseKey = "palms_back_flexor_stretch.wrong_forced",
                    rightPoseKey = "palms_back_flexor_stretch.right_slow_pulses",
                ),
            ),
            ladder = listOf(
                level("Fingers Out and Back, Light Lean", "Gentle introduction to the position."),
                level("Fingers Back, Deep Lean", "More lean, still comfortable."),
                level("Fingers Back, Hips to Heels", "Rock all the way to the heels."),
                level("Fingers Back, Knees Lifted", "Highest wrist-extension demand."),
            ),
            startLevel = 0,
        ),
        Exercise(
            id = "dorsal_wrist_pushups",
            name = "Dorsal (Back-of-Hand) Wrist Push-ups",
            summary = "Fists with the back of the hand on the floor; load about 15% of bodyweight and clench rhythmically.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(FOREARM_EXTENSORS, PRIMARY, END),
                tendon(LATERAL_ELBOW, SECONDARY, END, "Extensor origin"),
                joint(WRIST, PRIMARY, END, "Dorsal ligaments"),
            ),
            setupCues = listOf(
                "Kneel and place the backs of the hands flat on the floor with the fingers lightly curled.",
                "Keep the elbows locked and shift only enough weight to load about 15% of bodyweight.",
            ),
            executionCues = listOf(
                "Gently clench and release the fists 10 times while keeping the wrist neutral.",
                "Keep the shoulders over the wrists and avoid bouncing.",
                "Stop immediately if you feel sharp pain on the back of the wrist.",
            ),
            jointProtection = "Conditions the dorsal wrist ligaments and extensor tendons for straight-arm loading.",
            doDonts = listOf(
                DoDont(
                    title = "Load",
                    wrongLabel = "Full bodyweight on the knuckles",
                    wrongText = "Leaning all the way forward onto the backs of the hands.",
                    wrongConsequence = "Too much load on cold ligament and tendon tissue.",
                    rightLabel = "About 15% bodyweight",
                    rightText = "Most of the weight stays in the knees; hands carry a light load.",
                    wrongPoseKey = "dorsal_wrist_pushups.wrong_heavy_load",
                    rightPoseKey = "dorsal_wrist_pushups.right_light_load",
                ),
            ),
            ladder = listOf(
                level("10% Bodyweight", "Very light introduction."),
                level("15% Bodyweight", "Standard warm-up load."),
                level("25% Bodyweight", "Progressive extra load."),
                level("Plank Position", "Full bodyweight on the backs of the hands."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "passive_dead_hang",
            name = "Passive Dead Hang",
            summary = "Hang from a bar with relaxed shoulders to decompress the spine and stretch the lats and shoulder capsule.",
            category = MovementCategory.MOBILITY,
            kind = ExerciseKind.HOLD,
            highlights = listOf(
                muscle(LATS, PRIMARY, STEADY, "Long stretch"),
                muscle(FOREARM_FLEXORS, PRIMARY, STEADY, "Grip endurance"),
                tendon(MEDIAL_ELBOW, SECONDARY, STEADY, "Grip load on the flexor origin"),
                joint(SHOULDER_JOINT, SECONDARY, STEADY, "Capsule decompression"),
            ),
            setupCues = listOf(
                "Use an Active Hook Grip at the base of the fingers with the thumb wrapped.",
                "Keep the feet off the floor, or lightly touching if you need help.",
            ),
            executionCues = listOf(
                "Let the shoulders rise naturally and relax the neck.",
                "Warm-up: hang for 15 seconds.",
                "Decompression finisher: 2 sets of 45 seconds with a slow 4-second exhale.",
            ),
            jointProtection = "Passive hanging tractions the spine and conditions the finger flexors, ligaments and shoulder capsule.",
            doDonts = listOf(
                DoDont(
                    title = "Bar grip",
                    wrongLabel = "Bar deep in the palm crease",
                    wrongText = "Gripping the bar down in the crease of the palm.",
                    wrongConsequence = "Pinches the skin and rips calluses; the bar slides and the grip fatigues early.",
                    rightLabel = "Active Hook Grip",
                    rightText = "Bar at the base of the fingers with the thumb wrapped over.",
                    wrongPoseKey = "detail.grip_palm_crease",
                    rightPoseKey = "detail.grip_hook",
                ),
            ),
            ladder = listOf(
                level("Feet-Assisted Hang", "Toes on the floor to unload part of the weight."),
                level("Two-Arm Dead Hang", "Full bodyweight hang."),
                level("Active Hang", "Depress the shoulders without bending the elbows."),
                level("Weighted Dead Hang", "Add about 5 kg."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "scapular_pullups",
            name = "Scapular Pull-ups",
            summary = "Straight-arm shoulder-blade depression from a dead hang.",
            category = MovementCategory.PULL,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(LOWER_TRAPS, PRIMARY, END),
                muscle(LATS, SECONDARY, END),
                muscle(SERRATUS, SECONDARY, END),
                joint(SHOULDER_JOINT, SECONDARY, END, "Learns to stay packed"),
            ),
            setupCues = listOf(
                "Hang with straight arms and a hook grip.",
                "Start from relaxed shoulders.",
            ),
            executionCues = listOf(
                "Pull the shoulder blades down and back without bending the elbows.",
                "Hold the top position for 2 seconds, then lower slowly to a full hang.",
                "Complete 10 reps.",
            ),
            jointProtection = "Trains the shoulder-blade depressors so the shoulder joint and biceps tendon are not overloaded at the bottom of a pull-up.",
            doDonts = listOf(
                DoDont(
                    title = "Elbow position",
                    wrongLabel = "Bending the elbows to pull",
                    wrongText = "Pulling with bent elbows until the chin rises.",
                    wrongConsequence = "It becomes a lazy pull-up and the scapular muscles never learn to work.",
                    rightLabel = "Elbows locked",
                    rightText = "Arms stay straight and only the shoulder blades move.",
                    wrongPoseKey = "scapular_pullups.wrong_bent_elbows",
                    rightPoseKey = "scapular_pullups.right_straight_arm",
                ),
            ),
            ladder = listOf(
                level("Feet-Assisted Scapular Pull-up", "Toes on the floor take some load."),
                level("Strict Scapular Pull-up", "Full bodyweight, 2 second pause at the top."),
                level("Slow Eccentric Scapular Pull-up", "4 second controlled lowering."),
                level("Scapular Pull-up, 5 Second Hold", "Hold the top for 5 seconds."),
            ),
            startLevel = 1,
        ),
        Exercise(
            id = "scapular_dips",
            name = "Parallel Bar Support Hold + Scapular Dips",
            summary = "Locked-elbow support on parallel bars, then dip and shrug the shoulder blades only.",
            category = MovementCategory.PUSH,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(LOWER_TRAPS, PRIMARY, END),
                muscle(SERRATUS, PRIMARY, END),
                muscle(TRICEPS, SECONDARY, STEADY, "Isometric lockout"),
                tendon(MEDIAL_ELBOW, SECONDARY, STEADY, "Locked-elbow loading"),
                joint(SHOULDER_JOINT, SECONDARY, STEADY),
            ),
            setupCues = listOf(
                "Jump up into a straight-arm support with the elbows locked and the bars at hip level.",
                "Lean the chest slightly forward.",
            ),
            executionCues = listOf(
                "Hold the support first, then let the shoulders rise toward the ears and press them back down.",
                "The elbows stay locked for all 10 reps.",
                "Keep the ribs stacked and avoid swinging.",
            ),
            jointProtection = "Teaches shoulder depression in the dip lockout, protecting the anterior capsule and the elbow.",
            doDonts = listOf(
                DoDont(
                    title = "Support position",
                    wrongLabel = "Bent elbows, sagging shoulders",
                    wrongText = "Elbows soft and shoulders collapsing up around the ears.",
                    wrongConsequence = "Collapsing into the shoulder joint stresses the anterior capsule.",
                    rightLabel = "Locked and tall",
                    rightText = "Elbows locked and the shoulders pushed down away from the ears.",
                    wrongPoseKey = "scapular_dips.wrong_sagging",
                    rightPoseKey = "scapular_dips.right_depressed",
                ),
            ),
            ladder = listOf(
                level("Bench-Supported Scapular Dips", "Feet on the floor take some load."),
                level("Parallel Bar Support Hold", "Static support with locked elbows."),
                level("Scapular Dips", "10 reps with locked elbows."),
                level("Support Hold with Forward Lean", "Lean the shoulders forward over the hands."),
            ),
            startLevel = 2,
        ),
        Exercise(
            id = "scapular_pushups",
            name = "Scapular Push-ups",
            summary = "Straight-arm plank; protract and retract the shoulder blades without bending the elbows.",
            category = MovementCategory.PUSH,
            kind = ExerciseKind.REPS,
            highlights = listOf(
                muscle(SERRATUS, PRIMARY, END, "Protraction"),
                muscle(PEC_MINOR, SECONDARY, END),
                muscle(LOWER_TRAPS, SECONDARY, START),
                joint(SHOULDER_JOINT, MINOR, STEADY),
            ),
            setupCues = listOf(
                "Start in a high plank with the hands under the shoulders and the elbows locked.",
            ),
            executionCues = listOf(
                "Push the floor away to round the upper back at the top (full protraction).",
                "Let the chest sink between the shoulder blades without bending the elbows.",
                "Complete 10 reps with a 1 second pause at full protraction.",
            ),
            jointProtection = "The serratus anterior anchors the shoulder blade so the rotator cuff and biceps tendon are protected.",
            doDonts = listOf(
                DoDont(
                    title = "Elbows",
                    wrongLabel = "Elbows bending",
                    wrongText = "Letting the elbows bend into a small push-up.",
                    wrongConsequence = "It hides weakness in the shoulder-blade stabilizers.",
                    rightLabel = "Locked elbows",
                    rightText = "Full upper-back protraction at the top with straight arms.",
                    wrongPoseKey = "scapular_pushups.wrong_elbow_bend",
                    rightPoseKey = "scapular_pushups.right_protracted",
                ),
            ),
            ladder = listOf(
                level("Wall Scapular Push-ups", "Standing, hands on a wall."),
                level("Knees-Down Scapular Push-ups", "Kneeling plank."),
                level("Plank Scapular Push-ups", "Full plank."),
                level("Feet-Elevated Scapular Push-ups", "Feet on a bench."),
            ),
            startLevel = 2,
        ),
    )
}
